// This file was auto-generated by ML.NET Model Builder and then refactored for CLI training options.
using System.Globalization;
using System.Text.Json;
using System.Diagnostics;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Transforms;

namespace MLTest;

public partial class SentimentModel
{
    public const string RetrainFilePath = "Student_mental_health_data.csv";
    public const char RetrainSeparatorChar = ',';
    public const bool RetrainHasHeader = true;
    public const bool RetrainAllowQuoting = false;

    private const string LabelColumnName = "YearOfStudy";
    private const string FeatureColumnName = "Features";

    public sealed class TrainingOptions
    {
        public required string DataPath { get; init; }
        public required string ModelOutputPath { get; init; }
        public string Trainer { get; init; } = "lbfgs";
        public int Seed { get; init; } = 42;
        public float TestFraction { get; init; } = 0.2f;
        public string? RunName { get; init; }
        public string? MetadataDirectory { get; init; }

        // Optional parameters, mainly used for LightGBM.
        public float? LearningRate { get; init; }
        public int? NumberOfLeaves { get; init; }
        public int? NumberOfIterations { get; init; }
        public int? MaxBins { get; init; }
        public float? L2 { get; init; }
    }

    public sealed class TrainingResult
    {
        public required string RunId { get; init; }
        public required string Trainer { get; init; }
        public required int Seed { get; init; }
        public required float TestFraction { get; init; }
        public required string DataPath { get; init; }
        public required string ModelPath { get; init; }
        public required DateTimeOffset TrainedAtUtc { get; init; }
        public required double MacroAccuracy { get; init; }
        public required double MicroAccuracy { get; init; }
        public required double LogLoss { get; init; }
        public required double LogLossReduction { get; init; }
        public required double DurationSeconds { get; init; }
        public required string MetadataJsonlPath { get; init; }
        public required string MetadataCsvPath { get; init; }
        public required IReadOnlyList<string> Warnings { get; init; }
    }

    private sealed class TrainingRunMetadata
    {
        public required string RunId { get; init; }
        public string? RunName { get; init; }
        public required string Trainer { get; init; }
        public required int Seed { get; init; }
        public required float TestFraction { get; init; }
        public required string DataPath { get; init; }
        public required string ModelPath { get; init; }
        public required string TrainedAtUtc { get; init; }
        public required double MacroAccuracy { get; init; }
        public required double MicroAccuracy { get; init; }
        public required double LogLoss { get; init; }
        public required double LogLossReduction { get; init; }
        public required double DurationSeconds { get; init; }

        public float? LearningRate { get; init; }
        public int? NumberOfLeaves { get; init; }
        public int? NumberOfIterations { get; init; }
        public int? MaxBins { get; init; }
        public float? L2 { get; init; }

        public List<string> Warnings { get; init; } = [];
    }

    /// <summary>
    /// Backward-compatible training entry point.
    /// </summary>
    public static void Train(
        string outputModelPath,
        string inputDataFilePath = RetrainFilePath,
        char separatorChar = RetrainSeparatorChar,
        bool hasHeader = RetrainHasHeader,
        bool allowQuoting = RetrainAllowQuoting)
    {
        _ = separatorChar;
        _ = hasHeader;
        _ = allowQuoting;

        TrainWithOptions(new TrainingOptions
        {
            DataPath = inputDataFilePath,
            ModelOutputPath = outputModelPath,
            Trainer = "lbfgs",
            Seed = 42,
            TestFraction = 0.2f
        });
    }

    public static TrainingResult TrainWithOptions(TrainingOptions options)
    {
        ValidateTrainingOptions(options);
        var stopwatch = Stopwatch.StartNew();

        var normalizedTrainer = NormalizeTrainerName(options.Trainer);
        var warnings = new List<string>();

        var mlContext = new MLContext(seed: options.Seed);
        var data = LoadIDataViewFromFile(
            mlContext,
            options.DataPath,
            RetrainSeparatorChar,
            RetrainHasHeader,
            RetrainAllowQuoting);

        var split = mlContext.Data.TrainTestSplit(
            data,
            testFraction: options.TestFraction,
            seed: options.Seed);

        var pipeline = BuildPipeline(mlContext, options, normalizedTrainer, warnings);
        var model = pipeline.Fit(split.TrainSet);

        SaveModel(mlContext, model, split.TrainSet, options.ModelOutputPath);

        var predictions = model.Transform(split.TestSet);
        var metrics = mlContext.MulticlassClassification.Evaluate(
            predictions,
            labelColumnName: LabelColumnName,
            predictedLabelColumnName: "PredictedLabel");

        stopwatch.Stop();

        var trainedAt = DateTimeOffset.UtcNow;
        var runId = Guid.NewGuid().ToString("N", CultureInfo.InvariantCulture);
        var metadataDir = ResolveMetadataDirectory(options.MetadataDirectory, options.ModelOutputPath);

        var metadata = new TrainingRunMetadata
        {
            RunId = runId,
            RunName = options.RunName,
            Trainer = normalizedTrainer,
            Seed = options.Seed,
            TestFraction = options.TestFraction,
            DataPath = Path.GetFullPath(options.DataPath),
            ModelPath = Path.GetFullPath(options.ModelOutputPath),
            TrainedAtUtc = trainedAt.ToString("O", CultureInfo.InvariantCulture),
            MacroAccuracy = metrics.MacroAccuracy,
            MicroAccuracy = metrics.MicroAccuracy,
            LogLoss = metrics.LogLoss,
            LogLossReduction = metrics.LogLossReduction,
            DurationSeconds = stopwatch.Elapsed.TotalSeconds,
            LearningRate = options.LearningRate,
            NumberOfLeaves = options.NumberOfLeaves,
            NumberOfIterations = options.NumberOfIterations,
            MaxBins = options.MaxBins,
            L2 = options.L2,
            Warnings = warnings
        };

        var metadataJsonlPath = Path.Combine(metadataDir, "training_runs.jsonl");
        var metadataCsvPath = Path.Combine(metadataDir, "training_runs.csv");
        PersistMetadata(metadata, metadataJsonlPath, metadataCsvPath);

        return new TrainingResult
        {
            RunId = runId,
            Trainer = normalizedTrainer,
            Seed = options.Seed,
            TestFraction = options.TestFraction,
            DataPath = Path.GetFullPath(options.DataPath),
            ModelPath = Path.GetFullPath(options.ModelOutputPath),
            TrainedAtUtc = trainedAt,
            MacroAccuracy = metrics.MacroAccuracy,
            MicroAccuracy = metrics.MicroAccuracy,
            LogLoss = metrics.LogLoss,
            LogLossReduction = metrics.LogLossReduction,
            DurationSeconds = stopwatch.Elapsed.TotalSeconds,
            MetadataJsonlPath = metadataJsonlPath,
            MetadataCsvPath = metadataCsvPath,
            Warnings = warnings
        };
    }

    public static IDataView LoadIDataViewFromFile(
        MLContext mlContext,
        string inputDataFilePath,
        char separatorChar,
        bool hasHeader,
        bool allowQuoting)
    {
        return mlContext.Data.LoadFromTextFile<ModelInput>(
            inputDataFilePath,
            separatorChar,
            hasHeader,
            allowQuoting: allowQuoting);
    }

    public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
    {
        DataViewSchema dataViewSchema = data.Schema;
        var modelDir = Path.GetDirectoryName(modelSavePath);
        if (!string.IsNullOrWhiteSpace(modelDir) && !Directory.Exists(modelDir))
        {
            Directory.CreateDirectory(modelDir);
        }

        using var fs = File.Create(modelSavePath);
        mlContext.Model.Save(model, dataViewSchema, fs);
    }

    public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
    {
        var pipeline = BuildPipeline(mlContext);
        return pipeline.Fit(trainData);
    }

    public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
    {
        var options = new TrainingOptions
        {
            DataPath = RetrainFilePath,
            ModelOutputPath = "SentimentModel.mlnet"
        };

        return BuildPipeline(mlContext, options, NormalizeTrainerName(options.Trainer), warnings: []);
    }

    private static IEstimator<ITransformer> BuildPipeline(
        MLContext mlContext,
        TrainingOptions options,
        string normalizedTrainer,
        List<string> warnings)
    {
        var preprocessing = mlContext.Transforms.Categorical.OneHotEncoding(
                "Gender",
                "Gender",
                outputKind: OneHotEncodingEstimator.OutputKind.Indicator)
            .Append(mlContext.Transforms.ReplaceMissingValues(new[]
            {
                new InputOutputColumnPair("Age", "Age"),
                new InputOutputColumnPair("GPA", "GPA")
            }))
            .Append(mlContext.Transforms.Text.FeaturizeText(
                inputColumnName: "Major",
                outputColumnName: "Major"))
            .Append(mlContext.Transforms.Concatenate(
                FeatureColumnName,
                new[] { "Gender", "Age", "GPA", "Major" })) // StudentID intentionally excluded.
            .Append(mlContext.Transforms.Conversion.MapValueToKey(
                outputColumnName: LabelColumnName,
                inputColumnName: LabelColumnName,
                addKeyValueAnnotationsAsText: false));

        var trainer = CreateTrainerEstimator(mlContext, options, normalizedTrainer, warnings);

        return preprocessing
            .Append(trainer)
            .Append(mlContext.Transforms.Conversion.MapKeyToValue(
                outputColumnName: "PredictedLabel",
                inputColumnName: "PredictedLabel"));
    }

    private static IEstimator<ITransformer> CreateTrainerEstimator(
        MLContext mlContext,
        TrainingOptions options,
        string normalizedTrainer,
        List<string> warnings)
    {
        switch (normalizedTrainer)
        {
            case "lbfgs-maxent":
            {
                WarnUnusedForNonLightGbm(options, warnings, normalizedTrainer);

                var trainerOptions = new LbfgsMaximumEntropyMulticlassTrainer.Options
                {
                    LabelColumnName = LabelColumnName,
                    FeatureColumnName = FeatureColumnName
                };

                if (options.L2.HasValue)
                {
                    trainerOptions.L2Regularization = options.L2.Value;
                }

                return mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(trainerOptions);
            }

            case "sdca-maxent":
            {
                WarnUnusedForNonLightGbm(options, warnings, normalizedTrainer);

                var trainerOptions = new SdcaMaximumEntropyMulticlassTrainer.Options
                {
                    LabelColumnName = LabelColumnName,
                    FeatureColumnName = FeatureColumnName
                };

                if (options.L2.HasValue)
                {
                    trainerOptions.L2Regularization = options.L2.Value;
                }

                return mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(trainerOptions);
            }

            case "lightgbm-multiclass":
            {
                var trainerOptions = new LightGbmMulticlassTrainer.Options
                {
                    LabelColumnName = LabelColumnName,
                    FeatureColumnName = FeatureColumnName
                };

                if (options.LearningRate.HasValue)
                {
                    trainerOptions.LearningRate = options.LearningRate.Value;
                }

                if (options.NumberOfLeaves.HasValue)
                {
                    trainerOptions.NumberOfLeaves = options.NumberOfLeaves.Value;
                }

                if (options.NumberOfIterations.HasValue)
                {
                    trainerOptions.NumberOfIterations = options.NumberOfIterations.Value;
                }

                if (options.MaxBins.HasValue)
                {
                    trainerOptions.MaximumBinCountPerFeature = options.MaxBins.Value;
                }

                if (options.L2.HasValue)
                {
                    warnings.Add("--l2 is currently ignored for trainer 'lightgbm-multiclass' in this ML.NET version.");
                }

                return mlContext.MulticlassClassification.Trainers.LightGbm(trainerOptions);
            }

            default:
                throw new InvalidOperationException($"Unsupported trainer '{options.Trainer}'.");
        }
    }

    private static void WarnUnusedForNonLightGbm(TrainingOptions options, List<string> warnings, string trainer)
    {
        if (options.LearningRate.HasValue)
        {
            warnings.Add($"--learning-rate is ignored for trainer '{trainer}'.");
        }

        if (options.NumberOfLeaves.HasValue)
        {
            warnings.Add($"--number-of-leaves is ignored for trainer '{trainer}'.");
        }

        if (options.NumberOfIterations.HasValue)
        {
            warnings.Add($"--number-of-iterations is ignored for trainer '{trainer}'.");
        }

        if (options.MaxBins.HasValue)
        {
            warnings.Add($"--max-bins is ignored for trainer '{trainer}'.");
        }
    }

    private static string NormalizeTrainerName(string trainer)
    {
        var key = (trainer ?? string.Empty).Trim().ToLowerInvariant();

        return key switch
        {
            "lbfgs" or "maxent" or "lbfgs-maxent" => "lbfgs-maxent",
            "sdca" or "sdca-maxent" => "sdca-maxent",
            "lightgbm" or "lgbm" or "lightgbm-multiclass" => "lightgbm-multiclass",
            _ => throw new ArgumentException(
                $"Unsupported trainer '{trainer}'. Supported: lbfgs, sdca, lightgbm.",
                nameof(trainer))
        };
    }

    private static string ResolveMetadataDirectory(string? requestedDirectory, string modelPath)
    {
        if (!string.IsNullOrWhiteSpace(requestedDirectory))
        {
            var resolved = Path.GetFullPath(requestedDirectory);
            Directory.CreateDirectory(resolved);
            return resolved;
        }

        var modelDir = Path.GetDirectoryName(Path.GetFullPath(modelPath)) ?? AppContext.BaseDirectory;
        var metadataDir = Path.Combine(modelDir, "training_runs");
        Directory.CreateDirectory(metadataDir);
        return metadataDir;
    }

    private static void PersistMetadata(TrainingRunMetadata metadata, string jsonlPath, string csvPath)
    {
        var json = JsonSerializer.Serialize(metadata);
        File.AppendAllText(jsonlPath, json + Environment.NewLine);

        var writeHeader = !File.Exists(csvPath);
        using var writer = new StreamWriter(csvPath, append: true);

        if (writeHeader)
        {
            writer.WriteLine("RunId,RunName,Trainer,Seed,TestFraction,DataPath,ModelPath,TrainedAtUtc,MacroAccuracy,MicroAccuracy,LogLoss,LogLossReduction,DurationSeconds,LearningRate,NumberOfLeaves,NumberOfIterations,MaxBins,L2,Warnings");
        }

        var warningText = metadata.Warnings.Count == 0
            ? string.Empty
            : string.Join(" | ", metadata.Warnings);

        var values = new[]
        {
            metadata.RunId,
            metadata.RunName ?? string.Empty,
            metadata.Trainer,
            metadata.Seed.ToString(CultureInfo.InvariantCulture),
            metadata.TestFraction.ToString("0.####", CultureInfo.InvariantCulture),
            metadata.DataPath,
            metadata.ModelPath,
            metadata.TrainedAtUtc,
            metadata.MacroAccuracy.ToString("0.######", CultureInfo.InvariantCulture),
            metadata.MicroAccuracy.ToString("0.######", CultureInfo.InvariantCulture),
            metadata.LogLoss.ToString("0.######", CultureInfo.InvariantCulture),
            metadata.LogLossReduction.ToString("0.######", CultureInfo.InvariantCulture),
            metadata.DurationSeconds.ToString("0.###", CultureInfo.InvariantCulture),
            metadata.LearningRate?.ToString(CultureInfo.InvariantCulture) ?? string.Empty,
            metadata.NumberOfLeaves?.ToString(CultureInfo.InvariantCulture) ?? string.Empty,
            metadata.NumberOfIterations?.ToString(CultureInfo.InvariantCulture) ?? string.Empty,
            metadata.MaxBins?.ToString(CultureInfo.InvariantCulture) ?? string.Empty,
            metadata.L2?.ToString(CultureInfo.InvariantCulture) ?? string.Empty,
            warningText
        };

        writer.WriteLine(string.Join(',', values.Select(EscapeCsv)));
    }

    private static string EscapeCsv(string value)
    {
        if (value.Contains(',') || value.Contains('"') || value.Contains('\r') || value.Contains('\n'))
        {
            return $"\"{value.Replace("\"", "\"\"")}\"";
        }

        return value;
    }

    private static void ValidateTrainingOptions(TrainingOptions options)
    {
        if (string.IsNullOrWhiteSpace(options.DataPath))
        {
            throw new ArgumentException("Training data path is required.", nameof(options));
        }

        if (!File.Exists(options.DataPath))
        {
            throw new FileNotFoundException($"Training data file not found: {options.DataPath}");
        }

        if (string.IsNullOrWhiteSpace(options.ModelOutputPath))
        {
            throw new ArgumentException("Model output path is required.", nameof(options));
        }

        if (options.TestFraction <= 0 || options.TestFraction >= 1)
        {
            throw new ArgumentOutOfRangeException(
                nameof(options.TestFraction),
                "--test-fraction must be between 0 and 1 (exclusive).");
        }
    }
}
